rccar_teleop_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.7

    enable_button: 6  # L2 shoulder button
    #enable_button: 7  # R2 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
