ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
 
    device: /dev/ttyACM0
    frame_id: gps_link

    uart1:
      #baudrate: 230400
      baudrate: 460800

    config_on_startup: false

    gnss:
      gps: true
      galileo: true
      beidou: true
      imes: false
      glonass: true
      qzss: true

    inf:
      all: false

    publish:
      all: true
